# Generated by Django 5.1.5 on 2025-02-19 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Veri',
                'verbose_name_plural': 'Veriler',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Ürün Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün Tipi',
                'verbose_name_plural': 'Ürün Tipleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Giriş Tarihi')),
                ('stock_code', models.CharField(max_length=100, verbose_name='Stok Kodu')),
                ('material_name', models.CharField(max_length=200, verbose_name='Malzeme Adı')),
                ('inc', models.CharField(max_length=100, verbose_name='INC')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Hammadde',
                'verbose_name_plural': 'Hammaddeler',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sorumlu Kişi',
                'verbose_name_plural': 'Sorumlu Kişiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('recipe_code', models.CharField(max_length=100, verbose_name='Reçete Kodu')),
                ('recipe_name', models.CharField(max_length=200, verbose_name='Reçete Adı')),
                ('project_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proje No')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proje Adı')),
                ('result', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sonuç')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.producttype', verbose_name='Ürün Tipi')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson', verbose_name='Sorumlu Kişi')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('project_no', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('recipe_code', models.CharField(max_length=50, verbose_name='Reçete Kodu')),
                ('recipe_name', models.CharField(max_length=255, verbose_name='Reçete Adı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson', verbose_name='Sorumlu Kişi')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('project_no', models.CharField(max_length=50, verbose_name='Proje No')),
                ('project_name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('recipe_code', models.CharField(max_length=50, verbose_name='Reçete Kodu')),
                ('recipe_name', models.CharField(max_length=255, verbose_name='Reçete Adı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arşivlenme Tarihi')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson', verbose_name='Sorumlu Kişi')),
            ],
            options={
                'verbose_name': 'Arşivlenmiş Proje',
                'verbose_name_plural': 'Arşivlenmiş Projeler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rawmaterial', verbose_name='Hammadde')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.recipe', verbose_name='Reçete')),
            ],
            options={
                'verbose_name': 'Reçete Hammaddesi',
                'verbose_name_plural': 'Reçete Hammaddeleri',
                'unique_together': {('recipe', 'material')},
            },
        ),
    ]
