# Generated by Django 5.1.5 on 2025-02-13 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Ürün Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
            ],
            options={
                'verbose_name': 'Ürün Tipi',
                'verbose_name_plural': 'Ürün Tipleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('stock_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=200)),
                ('inc', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sorumlu Kişi',
                'verbose_name_plural': 'Sorumlu Kişiler',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project_code', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('recipe_code', models.CharField(max_length=50)),
                ('recipe_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('project_no', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('recipe_code', models.CharField(max_length=50)),
                ('recipe_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('project_no', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('recipe_code', models.CharField(max_length=50)),
                ('recipe_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson')),
            ],
        ),
    ]
