# Generated by Django 5.1.5 on 2025-02-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='project_code',
        ),
        migrations.AddField(
            model_name='recipe',
            name='project_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.producttype'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
