# Generated by Django 5.1.5 on 2025-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_archivedproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('project_no', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('recipe_code', models.CharField(max_length=50)),
                ('recipe_name', models.CharField(max_length=255)),
                ('responsible_person', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
