# Generated by Django 5.1.5 on 2025-02-13 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_recipe_options_remove_recipe_project_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedproject',
            options={'ordering': ['-start_date'], 'verbose_name': 'Arşivlenmiş Proje', 'verbose_name_plural': 'Arşivlenmiş Projeler'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Veri', 'verbose_name_plural': 'Veriler'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Hammadde', 'verbose_name_plural': 'Hammaddeler'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date'], 'verbose_name': 'Reçete', 'verbose_name_plural': 'Reçeteler'},
        ),
        migrations.AlterModelOptions(
            name='responsibleperson',
            options={'ordering': ['name'], 'verbose_name': 'Sorumlu Kişi', 'verbose_name_plural': 'Sorumlu Kişiler'},
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='archived_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arşivlenme Tarihi'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Proje Adı'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='project_no',
            field=models.CharField(max_length=50, verbose_name='Proje No'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='recipe_code',
            field=models.CharField(max_length=50, verbose_name='Reçete Kodu'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='recipe_name',
            field=models.CharField(max_length=255, verbose_name='Reçete Adı'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson', verbose_name='Sorumlu Kişi'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='start_date',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Proje Adı'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_no',
            field=models.CharField(max_length=50, verbose_name='Proje No'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recipe_code',
            field=models.CharField(max_length=50, verbose_name='Reçete Kodu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recipe_name',
            field=models.CharField(max_length=255, verbose_name='Reçete Adı'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson', verbose_name='Sorumlu Kişi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='entry_date',
            field=models.DateField(verbose_name='Giriş Tarihi'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='inc',
            field=models.CharField(max_length=100, verbose_name='INC'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_name',
            field=models.CharField(max_length=200, verbose_name='Malzeme Adı'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.IntegerField(verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='stock_code',
            field=models.CharField(max_length=100, verbose_name='Stok Kodu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.producttype', verbose_name='Ürün Tipi'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proje Adı'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='project_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proje No'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_code',
            field=models.CharField(max_length=100, verbose_name='Reçete Kodu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=200, verbose_name='Reçete Adı'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson', verbose_name='Sorumlu Kişi'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sonuç'),
        ),
        migrations.AlterField(
            model_name='responsibleperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='responsibleperson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='responsibleperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
