# Generated by Django 5.1.5 on 2025-02-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_archivedproject_options_alter_data_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='RecipeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rawmaterial', verbose_name='Hammadde')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.recipe', verbose_name='Reçete')),
            ],
            options={
                'verbose_name': 'Reçete Hammaddesi',
                'verbose_name_plural': 'Reçete Hammaddeleri',
                'unique_together': {('recipe', 'material')},
            },
        ),
    ]
