# Generated by Django 5.1.5 on 2025-02-07 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_responsibleperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedproject',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson'),
        ),
    ]
