# Generated by Django 5.1.5 on 2025-02-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_archivedproject_responsible_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('stock_code', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=200)),
                ('inc', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project_code', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('recipe_code', models.CharField(max_length=50)),
                ('recipe_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.responsibleperson')),
            ],
        ),
    ]
