# Generated by Django 5.1.5 on 2025-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_producttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['code'], 'verbose_name': 'Ürün Tipi', 'verbose_name_plural': 'Ürün Tipleri'},
        ),
        migrations.AlterField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ürün Kodu'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ürün Adı'),
        ),
    ]
